### ISSUE TITLE
build.gradle for Android in IntelliJ IDEA

### ISSUE THREAD

**Issue by serhii-k** [libgdx/libgdx#2746]
Hello guys,

After upgrade to gradle:1.0.0 there is some issue when importing a project to IntelliJ IDEA.

For example. I've created a new libGDX project with the latest gdx-setup.jar (without an 'html' subproject). Once imported into IntelliJ IDEA, in the project explorer, only 'core', 'desktop' and 'ios' words are bolded ('android' is not).

When I open File -> Project Structure... -> Modules (under the "Project settings") -> android, there is no content root under "Sources" and "Dependencies" contains only Android API 21 Platform and <Module source>.

It looks like the build.gradle inside the 'android' folder doesn't work properly for new Gradle in IntelliJ IDEA.

I have tried to package an android release from the command line for one of my projects with several outside dependencies (gradlew android:assembleRelease) and the build was successful. So the issue is in the config for IDEA.

I have tried an older version of gdx-setup.jar (downloaded on 11/28/2014) that has dependency on com.android.tools.build:gradle:0.13+ . It generates new projects without such troubles.

I am new to Gradle and don't now how to resolve this issue on my own. Please, help me.

Kind regards,
Serhii

**Comment by Tom-Ski** [comment]
Change the version of com.android.tools.build:gradle: to 0.14+, instead of 1.0.0.
This is an issue with IDEA 14.0.2 and should be resolved in 14.0.3.

**Comment by serhii-k** [comment]
Hello Tom,

Thank you for your fast response!

Although changing 1.0.0 to 0.14+ makes 'android' also bold in the project explorer, but it doesn't resolve the dependencies. I hope this issue will be resolved in IDEA 14.0.3.

Anyway, thank you for your support! I really appreciate it.

Kind regards,
Serhii

**Comment by Tom-Ski** [comment]
You may need to re-import to fix those.

**Comment by serhii-k** [comment]
Hm, I have tried to create a new libGDX project, changed the gradle dependency to 0.14+, then imported this project to IDEA. And so, as a result, there is only one dependency inside Android module which is Android API 21 Platform. No core, no gdx...

**Comment by Tom-Ski** [comment]
If you take this to the [forum](http://www.badlogicgames.com/forum/viewforum.php?f=11) or join the irc (#libgdx on freenode) I can give you a hand.

**Comment by serhii-k** [comment]
Tom, I have just posted this to the forum:
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18006

I didn't know whether I should post your replies, so I have just posted the original post.

**Comment by serhii-k** [comment]
Thank you!
