### ISSUE TITLE
Http requests crush in distribution

### ISSUE THREAD

**Issue by philwang2010** [libgdx/libgdx#2761]
PathClassLoader: can't find '/private/var/mobile/Containers/Bundle/Application/1C6C0CD8-A7C8-4179-ABCE-78FB732FFF37/IOSLauncher.app/lib/boot/robovm-cacerts-full.jar'
java.lang.ExceptionInInitializerError
at com.android.org.conscrypt.TrustedCertificateKeyStoreSpi.(TrustedCertificateKeyStoreSpi.java)
at java.lang.reflect.Constructor.internalNewInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java)
at java.lang.Class.newInstance(Class.java)
at java.security.Provider$Service.newInstance(Provider.java)
at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java)
at java.security.KeyStore.getInstance(KeyStore.java)
at com.android.org.conscrypt.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java)
at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java)
at com.android.org.conscrypt.SSLParametersImpl.createDefaultTrustManager(SSLParametersImpl.java)
at com.android.org.conscrypt.SSLParametersImpl.getDefaultTrustManager(SSLParametersImpl.java)
at com.android.org.conscrypt.SSLParametersImpl.(SSLParametersImpl.java)
at com.android.org.conscrypt.SSLParametersImpl.getDefault(SSLParametersImpl.java)
at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.(OpenSSLSocketFactoryImpl.java)
at java.lang.reflect.Constructor.internalNewInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java)
at java.lang.Class.newInstance(Class.java)
at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java)
at javax.net.ssl.HttpsURLConnection$NoPreloadHolder.(HttpsURLConnection.java)
at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java)
at com.android.okhttp.OkHttpClient.copyWithDefaults(OkHttpClient.java)
at com.android.okhttp.OkHttpClient.open(OkHttpClient.java)
at com.android.okhttp.OkHttpClient.open(OkHttpClient.java)
at com.android.okhttp.HttpHandler.openConnection(HttpHandler.java)
at java.net.URL.openConnection(URL.java)
at com.badlogic.gdx.net.NetJavaImpl.sendHttpRequest(NetJavaImpl.java)
at com.badlogic.gdx.backends.iosrobovm.IOSNet.sendHttpRequest(IOSNet.java)
at com.mygdx.game.MyGdxGame.create(MyGdxGame.java)
at com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(IOSGraphics.java)
at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(IOSGraphics.java)
at org.robovm.apple.uikit.UIView.$cb$drawRect$(UIView.java)
at org.robovm.apple.uikit.UIApplication.main(Native Method)
at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
at com.mygdx.game.IOSLauncher.main(IOSLauncher.java)
Caused by: java.lang.NullPointerException
at com.android.org.conscrypt.TrustedCertificateStore.(TrustedCertificateStore.java)

Libgdx 1.5.3
Robovm 1.0.0.b3

call Gdx.net.sendHttpRequest 

Run as iOS Device APP is OK
but Pack to IPA and Run Will Throw This Error

**Comment by panli32811** [comment]
Yeah, I also hava a trouble the same to you

**Comment by philwang2010** [comment]
uninstall ur robovm plugin,and reinstall this version:1.0.0.201412311508 can fix this bug
but old version plugin can not compile arm64 ipa

**Comment by AmazingDreams** [comment]
I have the same problem

**Comment by BlueRiverInteractive** [comment]
This issue should be fixed with the next nightly version of RoboVM: https://github.com/robovm/robovm/issues/723

**Comment by philwang2010** [comment]
THX

**Comment by ebbybeh** [comment]
I am using the latest nightly and am still getting this issue. These are the params in my build file: 

classpath 'org.robovm:robovm-gradle-plugin:1.0.0-beta-03'
...
 gdxVersion = '1.5.4-SNAPSHOT'
 roboVMVersion = '1.0.0-SNAPSHOT'
