### ISSUE TITLE
About TextField

### ISSUE THREAD

**Issue by panli32811** [libgdx/libgdx#3091]
It works fine,but I found something about message text can be improved with it.
1.setAlignment(int align) does,t work when message text is visible.
2.There' no method like drawText(Batch batch, BitmapFont font, float x, float y) about drawing message text, thus if using distance field font, it's so difficult.

**Comment by NathanSweet** [comment]
Fixed alignment. See DistanceFieldFont.

**Comment by maltaisn** [comment]
Can this be reopened? #2 is not fixed, there's still no method that can be overriden to draw message text. From [`TextField.java`](https://github.com/libgdx/libgdx/blob/f2ed6b4a365922964eb06538f486d9526d1803af/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java#L337):
```java
if (displayText.length() == 0) {
    if (!focused && messageText != null) {
        // ...
        BitmapFont messageFont = style.messageFont != null ? style.messageFont : font;
        // replace this call with drawMessageText(...)
        messageFont.draw(batch, messageText, x + bgLeftWidth, y + textY + yOffset, 0, messageText.length(),
            width - bgLeftWidth - bgRightWidth, textHAlign, false, "...");
    }
} else {
    // ...
    drawText(batch, font, x + bgLeftWidth, y + textY + yOffset);
}

protected void drawText (Batch batch, BitmapFont font, float x, float y) {
    font.draw(batch, displayText, x + textOffset, y, visibleTextStart, visibleTextEnd, 0, Align.left, false);
}
```
As a result there's no straightforward way to draw the message text with the distance field font. A `drawMessageText` method would solve this. I can make a pull request if needed.
