### ISSUE TITLE
NPE in AndroidMouseHandler.java

### ISSUE THREAD

**Issue by donfuxx** [libgdx/libgdx#4121]
#### Reproduction steps/code
Sometimes on closing Android app the app crashes due to below NPE

#### Version of LibGDX and/or relevant dependencies
1.9.3

#### Stacktrace
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                              Process: com.appham.tilepuzzles.mushrooms.android.debug, PID: 4494
                                                                                              java.lang.NullPointerException: Attempt to invoke interface method 'com.badlogic.gdx.Graphics com.badlogic.gdx.Application.getGraphics()' on a null object reference
                                                                                                  at com.badlogic.gdx.backends.android.AndroidMouseHandler.onGenericMotion(AndroidMouseHandler.java:62)
                                                                                                  at com.badlogic.gdx.backends.android.AndroidInputThreePlus.onGenericMotion(AndroidInputThreePlus.java:47)
                                                                                                  at android.view.View.dispatchGenericMotionEventInternal(View.java:8575)
                                                                                                  at android.view.View.dispatchGenericMotionEvent(View.java:8562)
                                                                                                  at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                                                  at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1658)
                                                                                                  at android.view.View.dispatchGenericMotionEvent(View.java:8552)
                                                                                                  at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                                                  at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1658)
                                                                                                  at android.view.View.dispatchGenericMotionEvent(View.java:8552)
                                                                                                  at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                                                  at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1658)
                                                                                                  at android.view.ViewGroup.exitHoverTargets(ViewGroup.java:1740)
                                                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2819)
                                                                                                  at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2978)
                                                                                                  at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5496)
                                                                                                  at android.view.ViewRootImpl.die(ViewRootImpl.java:5473)
                                                                                                  at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:369)
                                                                                                  at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:324)
                                                                                                  at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
                                                                                                  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3742)
                                                                                                  at android.app.ActivityThread.access$1400(ActivityThread.java:151)
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

#### Please select the affected platforms
- [ ] Android

**Comment by Tom-Ski** [comment]
Should be fixed in latest snapshot.

**Comment by unordinarity** [comment]
Have same problem with Android and Linux when using `gdx.app.getGraphics().*` in 1.9.5-snapshot in nightly-20161102 build.
> Should be fixed in latest snapshot.
But already not fixed? Or I am doing something wrong?
