### ISSUE TITLE
Table cell debug boxes render in incorrect Y Position 

### ISSUE THREAD

**Issue by BoBIsHere86** [libgdx/libgdx#6363]
#### Issue details
In libGDX versions 1.9.12 and higher. If you turn on the scene2D table debugging. The Green cell boxes will be incorrectly positioned as it seems the Y value is Flipped. After discussion in the discord. It seems it's related to a change in the Table class about 4 months ago. 41e65e25cfd24ec72aaf01fbf1aa39e1001019b2

#### Reproduction steps/code
This could be reproduced by turning on the table debugging mode in libGDX versions 1.9.12 and higher.

#### Version of LibGDX and/or relevant dependencies
1.9.12 and 1.9.13

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by piotr-j** [comment]
I think the unnecessary y flip here is the likely cause @NathanSweet 
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Table.java#L1215

**Comment by NathanSweet** [comment]
Thanks piotr-j. Sorry for the trouble!

**Comment by tommyettinger** [comment]
And also thanks @BoBIsHere86 for reporting the issue when I was too lazy to post it myself! Thankfully, this only affected debugging, and didn't make the debug boxes entirely unusable (just harder to use, because they were upside-down). I do wonder how many people encountered this; it definitely is a head-tilt-producing issue when you first see the flipped boxes.

**Comment by slebed** [comment]
I just saw this and now I understand whats going on.  I've been trying to chase down why the debug boxes were in the wrong part of the frame.

**Comment by BoBIsHere86** [comment]
I think this fix introduced a new issue. While the GREEN debug boxes are now fixed in 1.9.14. The RED Cell boxes are now Flipped on the Y Axis instead.
This example is built off the TABLE wiki example:
 table.add(nameLabel).expand();
 table.add(nameText).width(100);
 table.row();
 table.add(addressLabel);
 table.add(addressText).width(100);

I've attached a picture which shows this same table in 1.9.11, 1.9.13, and 1.9.14

![image](https://user-images.githubusercontent.com/55356015/110271445-12abc100-7f96-11eb-9c8f-d60ca08b8e28.png)

**Comment by tommyettinger** [comment]
This is definitely still an issue, just applying to the red cell debug boxes rather than the green actor debug boxes. I attempted to fix it (by using `-currentY` instead of `currentY` on line 1193 of Table.java), but my attempt wasn't good enough for nested tables. @NathanSweet , I don't want to mess with scene2d.ui since you wrote pretty much all of it -- is a fix clear here?

**Comment by NathanSweet** [comment]
Hope it's all fixed this time!

<details><summary>Code used to repro</summary>

```
public class TableDebugTest extends GdxTest {
	SpriteBatch batch;
	Stage stage;
	Skin skin;

	public void create () {
		batch = new SpriteBatch();

		stage = new Stage();
		Gdx.input.setInputProcessor(stage);

		skin = new Skin(Gdx.files.internal("data/uiskin.json"));

		Table table = new Table();
		table.setFillParent(true);
		stage.addActor(table);

		Label nameLabel = new Label("Name:", skin);
		TextField nameText = new TextField("", skin);
		Label addressLabel = new Label("Address:", skin);
		TextField addressText = new TextField("", skin);

		table.debug();
		table.add(nameLabel).expand();
		table.add(nameText).width(100);
		table.row();
		table.add(addressLabel);
		table.add(addressText).width(100);
	}

	public void render () {
		ScreenUtils.clear(0.2f, 0.2f, 0.2f, 1);
		stage.act(Math.min(Gdx.graphics.getDeltaTime(), 1 / 30f));
		stage.draw();
	}

	public void resize (int width, int height) {
		stage.getViewport().update(width, height, true);
	}

	static public void main (String[] args) throws Exception {
		new LwjglApplication(new TableDebugTest());
	}
}
```
</details>
